
---
title: "Class Exercise"
author: "Quinhas Fernandes"
date: "02/05/2019"
output:
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE, echo=TRUE}

load(file=url("https://github.com/EvansDataScience/data/raw/master/crime.RData"))

```


```{r table, include=FALSE}
(CrimeTotal=table(crime$crimecat,crime$Occurred.DayTime))
```


```{r table_rel_PIPES, include=FALSE}
# using "pipes" to help readability:
library(magrittr)
(CrimeTotal=table(crime$crimecat,crime$Occurred.DayTime) %>% #create table and then...
        prop.table() %>% #compute proportion and then...
        '*'(100)%>% # multiply by 100 and then...
        round(2)) #...round to to decimals
```

```{r table_byCol, include=FALSE}
CrimeCol=table(crime$crimecat,crime$Occurred.DayTime)%>%
         prop.table(margin = 2) %>%   # 2 is % by column
         "*"(100) %>%
         round(3)
```

```{r convertToDFgg, include=FALSE}
df.T=as.data.frame(CrimeTotal) # table of proportion based on total
```

```{r include=FALSE}
names(df.T)=c('Crime','Daytime','Percent') #renaming
```

```{r flip_facet, include=FALSE}
df.C=as.data.frame(CrimeCol)
colnames(df.C)=c('Crime','Daytime','Percent')
```

Exercise 1

```{r echo=FALSE, "exercise 1 loliplot.", eval=TRUE}
library(ggplot2)

base10  = ggplot(df.C, aes(x = reorder(Crime, Percent), y = Percent ) ) 

lolliplot1=base10 + geom_segment(aes(y = 0, 
                                   x = reorder (Crime, Percent), 
                                   yend = Percent, 
                                   xend = Crime), color = "gray50") +
                   facet_wrap( ~ Daytime ,nrow = 1) +
                   coord_flip() + theme(axis.text.y = element_text(size=6,angle = 45)) +
                   geom_point(size=0.5, color="gray50") +
                labs(title = "Proportion of Types of Crimes by day-time of occurence",
                   subtitle = "2017 king county crimes analysis",
                    x ="Percent(%)", 
                    y = "Types of crime",
                    caption = "Fig.1: Represents proportion of types of crimes in king county by day-time

Source:Seattle Open Data portal") +
              theme(panel.background = element_rect(fill = "gray97",
                                                    colour = "black"),
                    plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5),
                  plot.subtitle = element_text(hjust=0.5)) 

lolliplot1
```

exercise 2

```{r Exercise2 heatDescending, echo=FALSE}
# heatplot
base  = ggplot(df.C, aes(x = Daytime, y = reorder(Crime, -Percent), fill = Percent)) 
heat1 = base +  geom_tile() 
heat2 = heat1 +scale_fill_gradient(low = "yellow", 
                                   high = "purple")

heat3 = heat2 + theme_classic() 

heat4 = heat3 + theme(axis.text.x = element_text(angle = 90, vjust = 0.6), 
                      legend.title = element_blank(), #no title for legend
                      legend.position="top", 
                      legend.direction="horizontal",
                      legend.key.width=unit(1, "cm"),
                      legend.key.height=unit(1, "cm")) 

heat5 = heat4 + labs(y="Crime") + theme(axis.text.x = element_text(size=7,angle = 45))

heat5
```

Exercise 3 : complete missing elements

```{r crimeTapply, include=FALSE}
crimeYear=crime[crime$DaysToReport>=365,]
tapply(crimeYear$DaysToReport,crimeYear$Precinct,length)
```


```{r crimeAfter2000, include=FALSE}
crimeY2000=crime[(crime$DaysToReport>=365) & (crime$year>=2000),]
tapply(crimeY2000$DaysToReport,crimeY2000$Precinct,length)
```


```{r convertYear, include=FALSE}
crimeY2000$YearsToReport=crimeY2000$DaysToReport/365
```


```{r yearsToRep, include=FALSE}
# no missing:
crimeYearGG=crimeY2000[complete.cases(crimeY2000$YearsToReport),]

```



```{r boxBYE, echo=FALSE}

base  = ggplot(crimeYearGG,aes(x=factor(year), y=YearsToReport))
plot1 = base + stat_summary(fun.y=min, # function for 'y' is min()
                           geom="line",
                           show.legend = T,size=1,
                           aes(group=1,col='Min')) +
                     stat_summary(fun.y=max,
                            geom="line",
                            linetype='dashed',
                            size=1,show.legend = F,
                            aes(group=1,col='Max')) + 
                      stat_summary(fun.y=median,
                            geom="line",size=2,
                              aes(group=1,col='Median')) +
                     scale_colour_manual(name="Trends",
                                      values=c("blue", "black","red")
                                      ) +
  labs(title = "Reporting time trend from 2000 to 2017",
         subtitle = "Crimes with reporting time greater than a year",
                    x ="Years", 
                    y = "Median time to report crime (yrs)",
                    caption = "Fig.1: shows a 17 years analysis of trends of time to report crimes among those who took more a year to report

Source:Seattle open portal") +
  theme(plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5),
                  plot.subtitle = element_text(hjust=0.5))
plot1 
```



```{r crimeWeek, include=FALSE}
# data preparation:

crimeWeek=crime[(crime$DaysToReport<365) & (crime$year>=2000),]

crimeWeek$WeeksToReport=crimeWeek$DaysToReport/7

crimeYearGG2=crimeWeek[complete.cases(crimeWeek$WeeksToReport) &complete.cases(crimeWeek$crimecat),]


```



```{r plotCrimeWeek, echo=FALSE}
#plotting it:
base = ggplot(crimeYearGG2,aes(x=factor(year), y=WeeksToReport)) 
mins = base + stat_summary(fun.y=min,size=1,
                           geom="line", linetype='dashed',show.legend = T,
                           aes(group=1,col='Min'))
minsMaxs= mins + stat_summary(fun.y=max,
                              geom="line",size=1,show.legend = F,
                              aes(group=1,col='Max'))
minsMaxsMd= minsMaxs + stat_summary(fun.y=median,
                                    geom="line",size=2,
                                    aes(group=1,col='Median'))
plot2=minsMaxsMd + scale_colour_manual(name="Trends",
                                      values=c("blue", "black","red")
                                      ) +
  labs(title = "Reporting time trend from 2000 to 2017",
         subtitle = "Crimes with reporting time lower than a year",
                    x ="Years", 
                    y = "Median time to report crime (yrs)",
                    caption = "Fig.1: shows a 17 years analysis of trends of time to report crimes among those who took lower than a year to report

Source:Seattle open portal") +
  theme(plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5),
                  plot.subtitle = element_text(hjust=0.5))
  
plot2 
```



```{r byCrime, echo=FALSE}
base= ggplot(crimeYearGG,
             aes(x = reorder(crimecat, YearsToReport, FUN = max), # reorder!
                 y=YearsToReport)) 
mins = base + stat_summary(fun.y=min,size=1,
                           geom="line", linetype='dashed',show.legend = T,
                           aes(group=1,col='Min'))
minsMaxs= mins + stat_summary(fun.y=max,
                              geom="line",size=1,show.legend = F,
                              aes(group=1,col='Max'))
minsMaxsMd= minsMaxs + stat_summary(fun.y=median, size=2,
                                    geom="line",
                                    aes(group=1,col='Median'))
plot3=minsMaxsMd + scale_colour_manual(name="Trends",
                                      values=c("blue", "black","red")) +
  labs(title = "Reporting time from 2000 to 2017 by crime category ",
         subtitle = "Crimes with reporting time greater than a year",
                    x ="Crime category", 
                    y = "Median time to report crime (yrs)",
                    caption = "Fig.1: shows a 17 years analysis of time to report crimes 
among those who took more a year to report by crime category

Source:Seattle open portal") +
  theme(plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5),
                  plot.subtitle = element_text(hjust=0.5))
plot3 + coord_flip()
```



```{r byCrime2, echo=FALSE}
base = ggplot(crimeYearGG2,
              aes(x = reorder(crimecat, WeeksToReport, FUN = max),
                  y=WeeksToReport)) 
mins = base + stat_summary(fun.y=min,size=1,
                           geom="line", linetype='dashed',show.legend = T,
                           aes(group=1,col='Min'))
minsMaxs= mins + stat_summary(fun.y=max,
                              geom="line",size=1,show.legend = F,
                              aes(group=1,col='Max'))
minsMaxsMd= minsMaxs + stat_summary(fun.y=median,size=2,
                                    geom="line",
                                    aes(group=2,col='Median'))
plot4=minsMaxsMd + scale_colour_manual(name="Trends",
                                      values=c("blue", "black","red")) +
  labs(title = "Reporting time from 2000 to 2017 by crime category ",
         subtitle = "Crimes with reporting time lower than a year",
                    x ="Crime category", 
                    y = "Median time to report crime (yrs)",
                    caption = "Fig.1: shows a 17 years analysis of time to report crimes 
among those who took lower than a year to report by crime category

Source:Seattle open portal") +
  theme(plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5),
                  plot.subtitle = element_text(hjust=0.5))
  
plot4+coord_flip()
```

Exercise 4: Complete missing elements


```{r aggregate, include=FALSE}
# 1. MEAN of days it takes to report a crime by neighborhood
daysByNeigh=tapply(crime$DaysToReport, crime$Neighborhood, mean,na.rm=T)
```


```{r include=FALSE}
# 2. PROPORTION of crimes by neighborhood
crimesByNeigh=tapply(crime$crimecat, crime$Neighborhood, length)%>%      
                     prop.table()%>%
                     "*"(100)%>% 
                     round(2) 
```



```{r include=FALSE}
library(tibble)
as.data.frame(daysByNeigh)%>%rownames_to_column()
```


```{r TOdataFrame, include=FALSE}
daysByNeigh=as.data.frame(daysByNeigh)%>%rownames_to_column()
crimesByNeigh=as.data.frame(crimesByNeigh)%>%rownames_to_column()
```



```{r mergeDFS, include=FALSE}
num_num=merge(daysByNeigh,crimesByNeigh) # 'row name' is the "key"
```



```{r echo=FALSE}
library(ggrepel)

base = ggplot(num_num, aes(daysByNeigh,crimesByNeigh,label=rowname)) 
plot1= base +  geom_point() 
plot1 + geom_text_repel(aes(label=ifelse(crimesByNeigh>=5,
                                         num_num$rowname, ""))) +
    labs(title = "Scatter plot of Neighborhood crimes by days to report crimes ",
                    x ="Days to report crime", 
                    y = "Crimes by Neighborhood",
                    caption = "Fig.1: shows the correlation between crimes by neighboorhood and time to report crimes

Source:Seattle open portal") +
  theme(plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5))
```


```{r hexbins, echo=TRUE}
library(ggrepel)
base = ggplot(num_num, aes(daysByNeigh,crimesByNeigh)) 
scatp1 = base +  geom_hex(bins = 10)
scatp2= scatp1 + geom_text_repel(aes(label=ifelse(crimesByNeigh>=5,
                                                  num_num$rowname,
                                                  ""))) +     
  labs(title = "Correlation of Neighborhood crimes by days to report crimes ",
                    x ="Days to report crime", 
                    y = "Crimes by Neighborhood",
                    caption = "Fig.1: shows the correlation between crimes by 
neighboorhood and time to report crimes

Source:Seattle open portal") +
  theme(plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5))
scatp2 + scale_fill_distiller(palette ="Greys",direction=1) 
```


```{r density, echo=FALSE}
base = ggplot(num_num, aes(daysByNeigh,crimesByNeigh)) 
scatp1 = base +  stat_density_2d(aes(fill = ..density..), 
                                 geom = "raster", contour = FALSE)
scatp2=scatp1+geom_text_repel(aes(label=ifelse(crimesByNeigh>=5,
                                               num_num$rowname, "")))
scatp3 = scatp2 +  theme(legend.position='none') 
scatp4= scatp3 + scale_fill_distiller(palette="Greys", direction=1) 

scatp5 = scatp4 +  scale_x_continuous(expand = c(0, 0)) + 
         scale_y_continuous(expand = c(0, 0)) +     
  labs(title = "Association of Neighborhood crimes by days to report crimes ",
                    x ="Days to report crime", 
                    y = "Crimes by Neighborhood",
                    caption = "Fig.1: shows the correlation between crimes by neighboorhood and time to report crimes

Source:Seattle open portal") +
  theme(plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5))

scatp5
```


